### Set up a new RSS feed (Plpware)
POST http://localhost:3000/rss
Content-Type: application/json

{
  "url": "https://pplware.sapo.pt/feed",
  "name": "Plpware",
  "pub_key": "npub1",
  "priv_key": "nsec1",
  "relay": "ws://127.0.0.1:9090/relay"
}

### Set up a new RSS feed (Oeste)
POST http://localhost:3000/rss
Content-Type: application/json

{
  "url": "https://revistaoeste.com/feed/",
  "name": "revistaoeste",
  "pub_key": "npub1",
  "priv_key": "nsec1",
  "relay": "ws://127.0.0.1:9090/relay"
}

### Get all RSS feeds
GET http://localhost:3000/rss

### Get all Events
GET http://localhost:3000/events